### ISSUE TITLE
Application Error while clicking on Accordion Item in Canvas

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio-builder#2173]
I was clicking through the Accordion Items, when this error popped up:

![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/a42b751d-1ffe-455d-b8dd-0d633c9efb70)

## ERROR TEXT:

**Application Error**
``` TypeError: Failed to fetch
    at Vr (https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:27:6264)
    at https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:33:1386
    at h (https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:2:3307)
    at st (https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:2:3699)
    at https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:1:27322
    at Array.map (<anonymous>)
    at Yr (https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:1:27315)
    at Ba (https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:1:22465)
    at Ne (https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:1:20759)
    at Object.Kr [as navigate] (https://webstudio-builder-zfci14egi-webstudio-is.vercel.app/build/_shared/chunk-NKYBJIWW.js:1:19538)

**Comment by kof** [comment]
Needs specific steps for reproduction

**Comment by GoharAkram** [comment]
It happened when I added the Accordion component and was clicking through the sub-components inside it in the navigator.

I reloaded page after this error and it worked okay. So I am not certain what triggered it exactly. However, I still posted the error just to be on the safe side.

@kof

**Comment by kof** [comment]
closing since not reproducible
